language: node_js
node_js:
- '4'
- node
deploy:
  provider: npm
  email: npm@jakubsynowiec.info
  api_key:
    secure: $NPM_KEY
  skip_cleanup: true
  on:
    tags: true
    repo: jsynowiec/good-sentry
