language: node_js
node_js:
- '4'
- '6'
- node
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    repo: jsynowiec/good-sentry
    node: '6'
